// import jwt from "jsonwebtoken";
// import userModel from "../db/modle/User.model.js";
// export const auth = (req, res, next) => {
//     const { authorization } = req.headers;
//     if(!authorization.startsWith(process.env.BEARERKEY))
//         return res.status(400).json({ message: "Invalid authorization" });
//     const token = authorization.split(process.env.BEARERKEY)[1];
//     jwt.verify(token, process.env.LOGINSECRET, (err, decoded) => {
//         if(decoded) {
//             const user = await userModel.findById(decoded.id).select("userName role");
//             if(!user){
//                 return res.status(404).json({ message: "not registered user" });
//             }
//             if(user.role=="User"){
//                 return res.status(403).json({ message: "not auth user" });
//             }
//             // The code below is generated by Copilot
//             // It assigns the user object to the request object
//             req.user = user;
//             // It calls the next middleware function
//             next();
//         } else {
//             return res.status(400).json({ message: "Invalid authorization" });
//         }
//     })
// }
